### PR TITLE
HPC2N information

### PR DESCRIPTION
**Pull request by pojeda**
Hi Michael,

here is the information from HPC2N,

/Pedro

### CODE REVIEW

**Review by sloede — COMMENTED** [review]
This LGTM, thank you very much for contributing HPC2N's info! Would you mind adding yourself to the [author's list](https://github.com/pojeda/julia-on-hpc-systems#authors) (sorted alphabetically by last name) as well? If not that's ok too - we can merge it as it is 😊

**Comment by pojeda** [comment]
Hi,

could you add my info or should I do an additional PR?
Pedro Ojeda @pojeda

/Pedro

**Comment by sloede** [comment]
You could just add it in your branch that you used for this PR and then push it; the PR will then update automatically. I think this would be the easiest.

**Comment by sloede** [comment]
If that doesn't work, I can add it in a separate step though, thus as you prefer :-)

**Comment by pojeda** [comment]
I pushed that modification /Pedro

**Comment by sloede** [comment]
@pojeda Thanks a lot, looking good now! Great to have HPC2N visible here!

**Pull request merged**
