### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by carstenbauer**

### CODE REVIEW

**Review by sloede — APPROVED** [review]
Thanks!

**Comment by carstenbauer** [comment]
BTW, I think the "should we provide pre-installed Julia packages (i.e. CUDA.jl, MPI.jl, etc.) besides Julia binaries and env variables and stuff" deserves a separate section. (Instead of, e.g., under MPI.jl, mention that NERSC does it.)

**Comment by carstenbauer** [comment]
I think the trend is to not provide packages, at least not in the primary Julia module. If anything, as an extra "JuliaPackages" module or whatever.

**Comment by sloede** [comment]
That is a very good point, thanks! I will not be able to change this myself today, since my time allocation for "fun stuff" has run out for the day 😬 But I'll happily merge PRs in that direction!

**Pull request merged**
